language: bash
sudo: required

os:
- osx

install:
  # Install Shellcheck (github.com/koalaman/shellcheck#travis-ci)
  #- scversion="stable" # or "v0.4.7", or "latest"
  #- wget "https://storage.googleapis.com/shellcheck/shellcheck-$scversion.linux.x86_64.tar.xz"
  #- tar --xz -xvf "shellcheck-$scversion.linux.x86_64.tar.xz"
  #- shellcheck() { "shellcheck-$scversion/shellcheck" "$@"; }
  #- shellcheck --version
  # OS X: install the dash and checkbashisms script
  - if test "$TRAVIS_OS_NAME" = osx; then brew update && brew install dash checkbashisms && pip install bashate; fi

script:
- tests/ostemper-shellchecks.sh


sudo: required
dist: trusty
language: bash

before_install:
    - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse"
    - sudo apt-get -qq update
    - sudo apt-get -t trusty-backports install shellcheck
    - sudo apt-get -t trusty-backports install checkbashisms
    - sudo pip install bashate

script:
- /bin/bash tests/ostemper-shellchecks.sh