language: bash
sudo: required

os:
- osx

install:
  # OS X: install the dash and checkbashisms script
  - brew update
  - brew install dash checkbashisms shellcheck
  # Install Shellcheck 
  - curl https://bootstrap.pypa.io/get-pip.py | sudo python
  - sudo -H pip install --user bashate

script:
- tests/ostemper-shellchecks.sh